//* These tests exercise the on-disk build cache directly: a save/load round
//* trip must preserve recorded mtimes, and a cache written by a different
//* zkdocs binary version must be treated as stale rather than silently
//* served (the regression this guards: pages generated by an old binary
//* kept the old footer/markup forever because only the cache schema
//* version, not the zkdocs version, invalidated the cache).
const std = @import("std");
const testz = @import("testz");
const zkdocs = @import("zkdocs");
const render = zkdocs.render;
const fix = @import("fixtures.zig");

pub fn saveLoadRoundTripPreservesSources() !void {
    const gpa = std.heap.page_allocator;
    const dir = "test_tmp_cache_roundtrip";
    defer std.Io.Dir.cwd().deleteTree(fix.g_Io, dir) catch {};
    try std.Io.Dir.cwd().createDirPath(fix.g_Io, dir);

    {
        var cache = render.cache_mod.Cache.init(fix.g_Io, gpa);
        defer cache.deinit();
        try cache.recordSource("sample.zig");
        try cache.save(dir);
    }

    var loaded = render.cache_mod.Cache.load(fix.g_Io, gpa, dir);
    defer loaded.deinit();
    try testz.expectTrue(loaded.sourceUnchanged("sample.zig"));
}

pub fn mismatchedAppVersionInvalidatesCache() !void {
    const gpa = std.heap.page_allocator;
    const dir = "test_tmp_cache_version";
    defer std.Io.Dir.cwd().deleteTree(fix.g_Io, dir) catch {};
    try std.Io.Dir.cwd().createDirPath(fix.g_Io, dir);

    {
        var cache = render.cache_mod.Cache.init(fix.g_Io, gpa);
        defer cache.deinit();
        try cache.recordSource("sample.zig");
        try cache.save(dir);
    }

    // Corrupt the persisted app_ver so it can never match the running
    // binary's version, simulating a cache left behind by an older build.
    const cache_path = try std.fmt.allocPrint(gpa, "{s}/{s}", .{ dir, render.cache_mod.CACHE_FILENAME });
    defer gpa.free(cache_path);
    const raw = try std.Io.Dir.cwd().readFileAlloc(fix.g_Io, cache_path, gpa, .limited(64 * 1024));
    defer gpa.free(raw);
    const patched = try std.mem.replaceOwned(u8, gpa, raw, "\"app_ver\":\"", "\"app_ver\":\"stale-binary-");
    defer gpa.free(patched);
    {
        const f = try std.Io.Dir.cwd().createFile(fix.g_Io, cache_path, .{});
        defer f.close(fix.g_Io);
        try f.writeStreamingAll(fix.g_Io, patched);
    }

    var loaded = render.cache_mod.Cache.load(fix.g_Io, gpa, dir);
    defer loaded.deinit();
    // A version mismatch must fall back to an empty cache instead of
    // reusing the previous (now stale) run's recorded mtimes.
    try testz.expectFalse(loaded.sourceUnchanged("sample.zig"));
}
